/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.UFSC.ine5612.trabalho.Telas;

import br.UFSC.ine5612.trabalho.Controlador.ControladorCompra;
import br.UFSC.ine5612.trabalho.Entidades.Produto;
import java.util.ArrayList;

/**
 *
 * @author Ismael
 */
public class TelaCupom extends javax.swing.JFrame {
    private static TelaCupom instancia;
  
            
    public static TelaCupom getInstancia() {
        if (instancia == null) {
            instancia = new TelaCupom();
        }
        return instancia;
    }       
    /**
     * Creates new form TelaCupom
     */
    public TelaCupom() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaCupom = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        totalCupom = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        okCupom = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabelaCupom.setAutoCreateRowSorter(true);
        tabelaCupom.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tabelaCupom.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tabelaCupom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código", "Produto", "Preço"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaCupom.setToolTipText("");
        tabelaCupom.setColumnSelectionAllowed(true);
        tabelaCupom.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabelaCupom.setMinimumSize(new java.awt.Dimension(80, 50));
        tabelaCupom.setRowHeight(25);
        tabelaCupom.setRowMargin(2);
        tabelaCupom.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabelaCupom.setShowHorizontalLines(false);
        tabelaCupom.setShowVerticalLines(false);
        jScrollPane2.setViewportView(tabelaCupom);
        tabelaCupom.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("Valor total do cupom:");

        totalCupom.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        totalCupom.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalCupom.setText("R$ 0,00");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Cupom fiscal");

        okCupom.setText("OK");
        okCupom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okCupomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(okCupom, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(totalCupom, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalCupom, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(okCupom, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okCupomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okCupomActionPerformed
        // TODO add your handling code here:
        ControladorCompra.getInstancia().showTelaInicial();
        dispose();
    }//GEN-LAST:event_okCupomActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton okCupom;
    private javax.swing.JTable tabelaCupom;
    private javax.swing.JLabel totalCupom;
    // End of variables declaration//GEN-END:variables

    public void setTabela(ArrayList<Produto> listProdutos) {
        int linha = 0;
        float precoTotal = 0;
        for (Produto p : listProdutos) {
            tabelaCupom.setValueAt(p.getCodProduto(), linha, 0);
            tabelaCupom.setValueAt(p.getNome(), linha, 1);
            String preco = String.valueOf(p.getPreco()).replace(".", ",");
            tabelaCupom.setValueAt("R$ " + preco, linha, 2);

            linha++;
            precoTotal += p.getPreco();
        }
        totalCupom.setText("R$ = " + String.valueOf(precoTotal).replace(".", ","));
        this.setVisible(true);
    }
}
